name: Spell Check

on:
  push:
    branches:
      - '**' # Ignore push events for tags: https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#filtering-push-events

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: sobolevn/misspell-fixer-action@master
        with:
          options: "-rsvnuR ApplicationLibCode/"
      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Fixes by misspell-fixer"
          title: "Typos fix by misspell-fixer"
          branch: spell-check-patches
          branch-suffix: random
